version: '3.8'

services:
  db:
    image: postgres:15-alpine
    container_name: ninthroom_db
    restart: always
    environment:
      POSTGRES_USER: ${POSTGRES_USER:-postgres}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD:-postgres}
      POSTGRES_DB: ${POSTGRES_DB:-ninthroom}
    ports:
      # HOST:CONTAINER
      # changed host port to 5433 to avoid conflict with Project 1
      - "5433:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

  api:
    build: .
    container_name: ninthroom_api
    restart: always
    ports:
      # HOST:CONTAINER
      # this opens port 8000 on your VPS.
      - "8001:8000"
    environment:
      DOMAIN: ${DOMAIN:-http://localhost}
      # the db is still listening on 5432.
      DATABASE_URL: postgresql://${POSTGRES_USER:-postgres}:${POSTGRES_PASSWORD:-postgres}@db:5432/${POSTGRES_DB:-ninthroom}
    depends_on:
      - db
    volumes:
      - .:/app

volumes:
  postgres_data:
